### ISSUE TITLE
Ability to save files on device (offline files)

### ISSUE THREAD

**Issue by georgeke** [uwblueprint/dancefest-mobile#39]
Potential library: https://github.com/itinance/react-native-fs

Save critique form data to an offline/local file.

**Comment by katrinacrisostomo** [comment]
@georgeke So this issue is just trying to take the critique data from the global state and save it as a file onto the phone ya?

We'll have another issue for handling saving the recording straight to the phone?

**Comment by georgeke** [comment]
Yep

**Comment by georgeke** [comment]
Also for the recording, expo records straight to a local file on the phone and it gives you an URI of that file. So we can just use that URI later on to upload to the cloud

**Comment by katrinacrisostomo** [comment]
Okay, I'm thinking we don't need to reeeally save the other stuff as actual files on the phone so as to not use crazy amounts of storage, esp since the recordings use up a lot of space already. 

I'm just gonna save it to something like `AsyncStorage` so that the data persists on the app even if the app is closed (global state does not persist).

As long as the stuff persists in the app even if it's closed I think that's fine. It's not like they're ever gonna be in a situation where they're never gonna connect back to internet again so they'll need it as actual files they can pull out of the phone

This will also let us not have to worry about saving to local storage android vs. ios, `AsyncStorage` is a react native thing and will work the same on both

`TODO:` Make sure that whenever app is opened, the last `AsyncStorage` data that holds all the data as well as which critiques have been synced and which haven't is reuploaded to the global state where it can be accessed to sync when there is internet
